import type { Metadata } from "next";
import { Poppins,Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
import { Montserrat } from 'next/font/google';
import Sidebar from "./components/sidebar";

const font=Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // choisis ce que tu veux
  variable: '--font-poppins',
});
const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
});
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ecole",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={font.variable} suppressHydrationWarning>
        <head />
        <body className=" text-black text-[16px] lg:text-[18px] sm:text-[16px] md:text-[16px] bg-gray-200 flex min-h-screen">
            <Sidebar/>
            <main className="flex-1 bg-fixed bg-gray-100 p-0 overflow-y-auto h-screen">
            {children}
            </main>
            <Toaster position="top-left" reverseOrder={false} />
        </body>
    </html>
  );
}
